#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get upgrade -y
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start